# Generated by Django 4.1.6 on 2023-02-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_fabric_type', models.CharField(max_length=1000)),
                ('colour', models.CharField(max_length=100)),
                ('sizes', models.CharField(choices=[('XS', 'Xtra small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Xtra large')], max_length=2)),
                ('product_description', models.CharField(max_length=500)),
            ],
        ),
    ]
