# Generated by Django 4.1.6 on 2023-02-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_otp',
            field=models.IntegerField(blank=True, default=987651),
        ),
    ]
